"""Add discount_amount to Order model

Revision ID: 0b37ce22cf96
Revises: 5daea5697ce6
Create Date: 2025-04-09 01:40:26.379798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b37ce22cf96'
down_revision = '5daea5697ce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('discount_amount')

    # ### end Alembic commands ###
