"""Add price to OrderItem

Revision ID: 7530d580f38c
Revises: b0bdf84ef678
Create Date: 2025-04-08 20:19:03.905812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7530d580f38c'
down_revision = 'b0bdf84ef678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
