"""Add percentage column to DiscountCode

Revision ID: fd8cd8dda206
Revises: fd8c39cf0a91
Create Date: 2025-04-08 23:59:42.665340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8cd8dda206'
down_revision = 'fd8c39cf0a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discount_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentage', sa.Float(), nullable=False))
        batch_op.drop_column('discount_percentage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discount_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_percentage', sa.FLOAT(), nullable=False))
        batch_op.drop_column('percentage')

    # ### end Alembic commands ###
